# Generated by Django 4.1 on 2022-08-30 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings_coffeeshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('path', models.FilePathField(path='../data/')),
                ('id_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings_coffeeshop.settingscoffeeshop')),
            ],
        ),
    ]
