# Generated by Django 4.1 on 2022-08-30 13:46

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coffeeshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsCoffeeShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_content', models.CharField(max_length=40)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None)),
                ('id_coffee_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.coffeeshop')),
            ],
        ),
    ]
