# Generated by Django 4.1 on 2022-09-21 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_coffeeshop', '0002_alter_settingscoffeeshop_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settingscoffeeshop',
            old_name='id_coffee_house',
            new_name='id_coffeeshop',
        ),
    ]
