# Generated by Django 4.1 on 2022-10-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=200, verbose_name=reversed),
        ),
    ]
