# Generated by Django 4.1 on 2022-09-21 16:26

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0002_coffeeshop_latitude_coffeeshop_longitude'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='coffeeshop',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
