# Generated by Django 4.1 on 2022-11-01 13:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0006_coffeeshop_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeshop',
            name='email',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), default=['t', 'e', 's', 't', '@', 't', 'e', 's', 't', '.', 't', 'e', 's', 't'], size=None),
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='social_networks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=['h', 't', 't', 'p', 's', ':', '/', '/', 'v', 'k', '.', 'c', 'o', 'm'], size=None),
        ),
    ]
