# Generated by Django 4.1 on 2022-11-01 15:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0007_coffeeshop_email_alter_coffeeshop_social_networks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeshop',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='telephone',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='88005553535', max_length=15), default=['88005553535'], size=None),
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='website',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(default='https://vk.com/feed'), default=['https://vk.com/feed'], size=None),
        ),
    ]
