# Generated by Django 4.1 on 2022-11-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0011_alter_coffeeshop_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeshop',
            name='opening_hours',
            field=models.TextField(default='8:00 - 22:00'),
        ),
    ]
