# Generated by Django 4.1 on 2022-11-02 14:10

import coffeeshop.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0012_alter_coffeeshop_opening_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeshop',
            name='email',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), default=coffeeshop.models.get_email_default, size=None),
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='website',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=coffeeshop.models.get_website_default, size=None),
        ),
    ]
