# Generated by Django 4.1 on 2022-11-10 13:32

import coffeeshop.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0014_alter_coffeeshop_social_networks'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeshop',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to=''), default=coffeeshop.models.get_images_default, size=None),
        ),
        migrations.AddField(
            model_name='coffeeshop',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=coffeeshop.models.get_tags_default, size=None),
        ),
    ]
