# Generated by Django 4.1 on 2022-09-01 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2022, 9, 1, 14, 36, 13, 745518)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/static/img/avatars/avatar.jpg', upload_to=''),
        ),
    ]
