# Generated by Django 4.1 on 2022-09-20 14:53

import datetime
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_profile_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
                ('manager', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2022, 9, 20, 14, 53, 34, 370548, tzinfo=datetime.timezone.utc)),
        ),
    ]
